### ISSUE TITLE
2nd Brain With Obsidian

### ISSUE THREAD

**Issue by ahmedsaheed** [ahmedsaheed/ahmed-Saheed#23]
Obsidian is a powerful knowledge base on top of a local folder of plain text Markdown files.
It seems like a great feature on my website as i have always wanted a garden & sencond brain like [this](https://github.com/jackyzha0/quartz)
I found this [guide](https://marcus.se.net/obsidian-plugin-docs/advanced-guides/react)

## TODO 

- [x] Understand Obsidian 
- [x] Notes are dynamically saved to garden's repo [Example ](https://github.com/amorriscode/anthonymorris.dev/tree/main/data)
- [x] Get Forced to use slugs for dynamic routing **It's not hard dude!**
- [ ] ~~Maybe Render The Graph [see here](https://github.com/jackyzha0/quartz/blob/34b0353797a0d24c309139034918ad2060f504f5/layouts/partials/graph.html#L1) and [here](https://github.com/jackyzha0/quartz/blob/34b0353797a0d24c309139034918ad2060f504f5/assets/js/graph.js#L1)~~
- [x] Add Some sort of search see [stork-search](https://stork-search.net/) and [flex-search](https://github.com/nextapps-de/flexsearch) and [here](https://github.com/angeloashmore/react-use-flexsearch) an [example](https://github.com/nextapps-de/flexsearch/blob/master/doc/0.7.0-lang.md)
- [x] Sesrch completed! Style the search. [Example](https://github.com/jackyzha0/quartz/blob/34b0353797a0d24c309139034918ad2060f504f5/assets/styles/base.scss#L402) 
- [x] Use the `ctrl + k` key. [See here](https://github.com/jackyzha0/quartz/blob/34b0353797a0d24c309139034918ad2060f504f5/assets/js/search.js#L237)

**Comment by ahmedsaheed** [comment]
Knocked Out
